version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "trivia-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1k5fsq0mgpt4c"
s3_prefix = "trivia-app"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
